sudo: required
language: generic


#tell travies we need a copy of docker running
services:
    - docker

before_install:
    - docker build -t ranger001/docker-react -f Dockerfile.dev .
#build our image using dockerfile.dev (since we want to run the test suite first)

#tell travis how to run our test suite
script:
    - docker run -e CI=true ranger001/docker-react npm run test -- --coverage

#tell travis how to deploy our code to AWS
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-052020738786"
    bueket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

